# Generated by Django 2.1.3 on 2018-11-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampStart', models.DateTimeField(auto_now_add=True)),
                ('timestampEnd', models.DateTimeField(auto_now_add=True)),
                ('latStart', models.FloatField()),
                ('lngStart', models.FloatField()),
                ('latEnd', models.FloatField()),
                ('lngEnd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QuakeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('parent_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathLogger.PathBlock')),
            ],
        ),
    ]
