# Generated by Django 2.1.3 on 2018-11-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathLogger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathcell',
            old_name='latEnd',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='pathcell',
            old_name='latStart',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='pathcell',
            old_name='timestampEnd',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='pathcell',
            name='lngEnd',
        ),
        migrations.RemoveField(
            model_name='pathcell',
            name='lngStart',
        ),
        migrations.RemoveField(
            model_name='pathcell',
            name='timestampStart',
        ),
    ]
