# Generated by Django 2.1.3 on 2018-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathLogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathblock',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
