# Generated by Django 2.1.3 on 2018-11-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResolvedPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latStart', models.FloatField()),
                ('lngStart', models.FloatField()),
                ('latEnd', models.FloatField()),
                ('lngEnd', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='resolveddelta',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathResolver.ResolvedPath'),
        ),
    ]
