# Generated by Django 2.1.3 on 2018-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathResolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolvedpath',
            name='color',
            field=models.FloatField(default=0.0),
        ),
    ]
